name: Build and Release

on:
  push:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 根据需要设置Python版本

    - name: Install dependencies and build
      run: |
        sudo apt update
        sudo apt install zip unzip
        pip install setuptools wheel
        python setup.py bdist_wheel sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}