name: Build and Release

on:
  workflow_dispatch:
    inputs:
      AppDTVersion:
        description: '输入版本号：'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 根据需要设置Python版本

    - name: Install dependencies and build
      run: |
        sudo apt update
        sudo apt install zip unzip
        pip install setuptools wheel
        python setup.py bdist_wheel sdist

    - name: Create setup.bat
      run: |
        echo "pip install AppDT-${{ github.event.inputs.AppDTVersion }}-py3-none-any.whl" >> dist/setup.bat
        echo "pause" >> dist/setup.bat

    - name: Package dist directory
      run: |
        zip -r dist.zip dist

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      with:
        tag_name: ${{ github.event.inputs.AppDTVersion }}
        release_name: ${{ github.event.inputs.AppDTVersion }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist.zip
        asset_name: dist.zip
        asset_content_type: application/zip
